config/routes.rb
Project1::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
            controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations", omniauth_callbacks: "authentications"}

  resources :students

  resources :teachers

  resources :classrooms do
    resources :teachers, :students
    
    
  end

root :to => 'classrooms#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  attr_accessible :name
  has_many :teachers
   has_many :students
 validates :name, :uniqueness => true
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  # GET /classrooms
  # GET /classrooms.json
  def index
    @classrooms = Classroom.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @classrooms }
    end
  end
  def power
    @classrooms = Classroom.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @classrooms }
    end
  end
  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
    @classroom = Classroom.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @classroom }
    end
  end

  # GET /classrooms/new
  # GET /classrooms/new.json
  def new
    @classroom = Classroom.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @classroom }
    end
  end

  # GET /classrooms/1/edit
  def edit
    @classroom = Classroom.find(params[:id])
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(params[:classroom])

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to classrooms_path, notice: 'Classroom was successfully created.' }
        format.json { render json: @classroom, status: :created, location: @classroom }
      else
        format.html { render action: "new" }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /classrooms/1
  # PUT /classrooms/1.json
  def update
    @classroom = Classroom.find(params[:id])

    respond_to do |format|
      if @classroom.update_attributes(params[:classroom])
        format.html { redirect_to @classroom, notice: 'Classroom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom = Classroom.find(params[:id])
    @classroom.destroy

    respond_to do |format|
      format.html { redirect_to classrooms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_form.html.erb
<%= form_for(@classroom) do |f| %>
  <% if @classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% @classroom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classrooms/edit.html.erb
<h1>Editing classroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @classroom %> |
<%= link_to 'Back', classrooms_path %>

app/views/classrooms/index.html.erb
<h1>Listing classrooms</h1>

<table class="table table-striped tabled-bordered table-hover">
  <tr>
    <th>Classroom Designation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @classrooms.each do |classroom| %>
  <tr>
    <td><%= link_to classroom.name, classroom %></td>
    <td><%= link_to 'View Class', classroom %></td>
    <td><%= link_to 'Edit Class', edit_classroom_path(classroom) %></td>
    <td><%= link_to 'Delete', classroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Classroom', new_classroom_path %>

app/views/classrooms/new.html.erb
<h1>New classroom</h1>

<%= render 'form' %>

<%= link_to 'Back', classrooms_path %>

app/views/classrooms/power.html.erb
<h1>Listing classrooms</h1>

<table class="table-striped">
  <tr>
    <th>This is the admin panel where you create your classroom name
</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @classrooms.each do |classroom| %>
  <tr>
    <td><%= classroom.name %></td>
    <td><%= link_to 'Show', classroom %></td>
    <td><%= link_to 'Edit', edit_classroom_path(classroom) %></td>
    <td><%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Classroom', new_classroom_path %>

app/views/classrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @classroom.name %>
</p>
<table class="table table-striped tabled-bordered table-hover table-condensed">
  <tr>
    <th>Teacher(s)</th>
  <th></th>
    <th></th>
  </tr>

  <% @classroom.teachers.each do |teacher| %>
    <tr>
      <td><%= link_to teacher.teacher_name, edit_classroom_teacher_path(@classroom, teacher) %></td>
    <td><%= link_to 'Edit Teacher', edit_teacher_path(teacher) %></td>
    <td><%= link_to 'Remove Teacher', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<p>
	<%= link_to 'New Teacher', new_classroom_teacher_path(@classroom)%>
</p>
<table class="table table-striped tabled-bordered table-hover table-condensed">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @classroom.students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= student.email %></td>
    <td><%= link_to 'Edit Student', edit_student_path(student) %></td>
    <td><%= link_to 'Remove Student', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<p>
	<%= link_to 'Add Student', new_classroom_student_path(@classroom)%>
</p>
<%= link_to 'Edit', edit_classroom_path(@classroom) %> |
<%= link_to 'Back', classrooms_path %>